const products = [
  {id:"nova",name:"NovaDrive",category:"Zubehör",price:14.99,image:"assets/products/nova.png",art:"128 GB",short:"USB 3.2 Gen 1 · recyceltes Aluminium",description:"Der kompakte USB-Stick mit 128 GB Speicher ist dein zuverlässiger Begleiter für Schule, Alltag und Freizeit. Schnell, robust und aus recyceltem Aluminium.",specs:"128 GB · USB 3.2 Gen 1 · 15 g"},
  {id:"reson",name:"ResonX Multi-Use Hairtool",category:"Smart Home",price:79.99,image:"assets/products/resonx.jpg",art:"RESON X",short:"Glätten · Föhnen · Kämmen · Stylen",description:"Glätten, föhnen, kämmen, locken und stylen – alles mit nur einem vielseitigen Gerät und besonders schonender Anwendung.",specs:"5-in-1 Styling · schonende Anwendung"},
  {id:"air",name:"4D Air Fryer",category:"Smart Home",price:179.99,image:"assets/products/airfryer-1.jpeg",gallery:["assets/products/airfryer-1.jpeg","assets/products/airfryer-2.jpeg"],art:"4D\nCOOK",short:"8 Liter · WLAN · 2.000 Watt",description:"Gleichmäßig knusprige Ergebnisse dank intelligenter 4D-Cooking-Technologie. Mit 8 Litern Fassungsvermögen, Touch-Display und Smartphone-App.",specs:"8 l · 2.000 W · 40–220 °C · ca. 7,2 kg"},
  {id:"mouse",name:"SmoothV2 Wireless Mouse",category:"Computer",price:37.99,art:"SMOOTH",short:"Leicht · kabellos · präzise",description:"Eine leichte, reaktionsschnelle Wireless-Maus für Büro, Schule und Homeoffice. Funktioniert auf Glas, Mauspad und glatten Untergründen.",specs:"73 g · USB-Empfänger · Wireless"},
  {id:"laptop",name:"Laptop 1000 Ultra Pro",category:"Computer",price:450,image:"assets/products/laptop.png",art:"17.3\nULTRA",short:"Ryzen 3 · 512 GB SSD · Wi-Fi 6",description:"Großes, entspiegeltes 17,3-Zoll-Full-HD-Display, leistungsstarker AMD Ryzen 3 und schneller 512 GB NVMe-Speicher für flüssiges Multitasking.",specs:"17,3″ FHD · Ryzen 3 · 512 GB SSD · 2,5 kg"},
  {id:"headset",name:"Groß StereoHeadset",category:"Audio",price:59.85,image:"assets/products/headset.jpeg",art:"SOUND",short:"ANC · kabellos · 24 h Akku",description:"Kristallklarer Sound und aktive Rauschunterdrückung für ablenkungsfreie Calls. Ergonomisch, kabellos und kompatibel mit gängigen Meeting-Plattformen.",specs:"ANC · 24 h Akkulaufzeit · 145 g"},
  {id:"clays",name:"Clay S5",category:"Entertainment",price:500,image:"assets/products/clays5.jpeg",art:"CLAY\nS5",short:"Gaming · Streaming · Multiplayer",description:"Die neueste Konsole für Videospiele jeder Art, Streaming und Online- oder lokalen Multiplayer – ohne zusätzliches Abo.",specs:"Gaming · Streaming · 4 kg"},
  {id:"monitor",name:"TechRevive ProView",category:"Computer",price:389.99,art:"4K\n120",short:"32″ · Ultra HD · 120 Hz",description:"Gestochen scharfe Ultra-HD-Auflösung mit augenschonender Darstellung. Die perfekte Übersicht für professionelles Arbeiten und Multitasking.",specs:"32″ · 4K UHD · 120 Hz · 3,9 kg"},
  {id:"power",name:"PowerHub 2.0",category:"Zubehör",price:49.90,art:"65W\nPOWER",short:"USB-C · Wireless · Reiseadapter",description:"Schnellladen, kabelloses Laden und internationale Adapter in einem kompakten Gerät. Das Display zeigt die aktuelle Ladeleistung in Echtzeit.",specs:"65 W · USB-C + USB-A · Wireless 15 W · 185 g"},
  {id:"switch",name:"Netzwerk Switch",category:"Zubehör",price:24.99,image:"assets/products/network-switch.png",art:"5-PORT",short:"Kompakt · zuverlässig · Plug & Play",description:"Der kompakte 5-Port-Switch verbindet PCs, Spielekonsolen, Smart-TVs und Drucker unkompliziert mit deinem Heim- oder Büronetzwerk.",specs:"5 Ports · Plug & Play · 220 g"}
];
let activeCategory = "Alle";
const euro = value => value.toLocaleString("de-AT",{style:"currency",currency:"EUR"});
const grid = document.querySelector("#productGrid");
function visibleProducts(){const search=document.querySelector("#searchInput").value.toLowerCase().trim();return products.filter(p=>(activeCategory==="Alle"||p.category===activeCategory)&&(!search||`${p.name} ${p.short} ${p.category}`.toLowerCase().includes(search)))}
function productVisual(p){return p.image?`<img class="product-image" src="${p.image}" alt="${p.name}" loading="lazy">`:`<div class="art-object">${p.art.split("\n").map((line,i)=>i?`<small>${line}</small>`:line).join("")}</div>`}
function renderProducts(){const list=visibleProducts();document.querySelector("#noResults").hidden=list.length>0;grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-art">${productVisual(p)}</div><div class="product-info"><span class="product-category">${p.category}</span><h3>${p.name}</h3><p>${p.short}</p><div class="product-bottom"><strong class="price">${euro(p.price)}</strong><button class="details-button" data-detail="${p.id}">Details ansehen <span>→</span></button></div></div></article>`).join("")}
function openDetails(id){const p=products.find(item=>item.id===id);const gallery=p.gallery?`<div class="modal-gallery">${p.gallery.map(src=>`<img src="${src}" alt="${p.name}">`).join("")}</div>`:"";document.querySelector("#modalBody").innerHTML=`<div class="modal-inner"><div class="product-art">${productVisual(p)}${gallery}</div><div><span class="product-category">${p.category}</span><h2>${p.name}</h2><p>${p.description}</p><div class="modal-specs">${p.specs}</div><div class="modal-price">${euro(p.price)}</div></div></div>`;document.querySelector("#productModal").classList.add("open")}
document.addEventListener("click",e=>{const detail=e.target.closest("[data-detail]");if(detail)openDetails(detail.dataset.detail)});
document.querySelectorAll(".category-tabs button").forEach(button=>button.addEventListener("click",()=>{document.querySelector(".category-tabs .active").classList.remove("active");button.classList.add("active");activeCategory=button.dataset.category;renderProducts()}));
document.querySelector("#searchInput").addEventListener("input",renderProducts);document.querySelector("#closeModal").addEventListener("click",()=>document.querySelector("#productModal").classList.remove("open"));document.querySelector(".modal-backdrop").addEventListener("click",()=>document.querySelector("#productModal").classList.remove("open"));
renderProducts();
